language: php
php:
  - 7.1
  - 7.2
  - nightly
services:
  - redis-server
install:
  - ./travisci-install.sh
before_script:
  - composer install
matrix:
  allow_failures:
    - php: nightly
    - php: 7.1
  fast_finish: true
