dist: bionic
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - setup=basic
    - setup=stable
    - setup=lowest

services:
  - redis-server

install:
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update

before_script:
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -c ./ --verbose

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
